jobs:
  run:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - name: Start
        uses: actions/checkout@v2
      - name: Download Dependencies
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Execute Unit Tests
        run: ./test/verify

name: Check

on:
  schedule:
    - cron: "50 */3 * * *"
